
import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react';
import NavBar from './components/navbar';
import Footer from './components/footer';
import {StateContext} from "../app/context/statecontext"
import {Toaster} from "react-hot-toast"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Es Jay Store',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.png',
  },
}

export default function RootLayout({children,}:{children: React.ReactNode}) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <StateContext>
    <Toaster/>
    <main className="main-container">
    <NavBar/>
     {children}
      </main>
      <Footer/>
      </StateContext>
      </body>
    </html>

  )
}
 